// Core Type Definitions for Open Arms Game

// ============================================================================
// Enums
// ============================================================================

export type ResidentProfile = 
  | "young_adult"
  | "veteran"
  | "elderly";

export type ResidentState = 
  | "idle"
  | "seeking_need"
  | "pathfinding"
  | "in_use"
  | "satisfied"
  | "sleeping";

export type Need = 
  | "food"
  | "bathroom"
  | "learning"
  | "social"
  | "sleep";

export type RoomType = 
  | "dormitory"
  | "cafeteria"
  | "learning_center"
  | "vocational_room"
  | "bathroom"
  | "admin_office"
  | "common_room"
  | "fundraiser_station";

export type TileType = 
  | "empty"
  | "locked"
  | "hallway"
  | "room"
  | "entrance";

export type FoodPortionSetting = "large" | "standard" | "small" | "none";

export type DayPhase = "day" | "night";

// ============================================================================
// Grid & Tile Structures
// ============================================================================

export interface Tile {
  x: number;
  y: number;
  type: TileType;
  occupiedBy: string | null;  // Room ID if occupied
  walkable: boolean;
}

export interface UnlockedArea {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

export interface Grid {
  width: number;
  height: number;
  tiles: Tile[][];
  unlockedArea: UnlockedArea;
}

// ============================================================================
// Pathfinding
// ============================================================================

export interface PathNode {
  x: number;
  y: number;
}

// ============================================================================
// Resident Data Model
// ============================================================================

export interface Resident {
  id: string;
  name: string;
  profile: ResidentProfile;
  
  // Stats
  happiness: number;        // 0-100
  lifeMeter: number;        // 0-100
  
  // State
  currentState: ResidentState;
  currentNeed: Need | null;
  targetRoomId: string | null;
  path: PathNode[] | null;
  pathIndex: number;
  
  // Position
  gridX: number;
  gridY: number;
  
  // Sleep position (locked position when sleeping)
  sleepX: number | null;
  sleepY: number | null;
  
  // History
  arrivalDay: number;
  arrivalReason: string;
  daysInShelter: number;
  
  // Timers
  lastHappinessUpdate: number;
  lastNeedCheck: number;
  lastLifeUpdate: number;
  lastMealTime: number;        // Timestamp of last meal
}

// ============================================================================
// Room Data Model
// ============================================================================

export interface Room {
  id: string;
  type: RoomType;
  
  // Grid placement
  gridX: number;
  gridY: number;
  width: number;
  height: number;
  
  // State
  isOpen: boolean;
  currentOccupancy: number;
  
  // Costs
  buildCost: number;
  maintenanceCost: number;
  lastMaintenancePaid: number;
  
  // Visual
  image?: string;  // Optional image path/key for room tile
}

export interface RoomSpec {
  type: RoomType;
  width: number;
  height: number;
  buildCost: number;
  maintenanceCost: number;
  capacity: number;
  closesAtNight: boolean;
  needsSatisfied: Need[];
  image?: string;  // Optional default image path/key for this room type
}

// ============================================================================
// Fundraiser Data Model
// ============================================================================

export interface Fundraiser {
  id: string;
  stationId: string;              // Room ID of fundraiser station
  startedAt: number;              // Timestamp
  duration: number;               // Duration in minutes
  completesAt: number;            // Timestamp
  assignedResidents: string[];    // Resident IDs
  expectedPayout: number;         // Calculated payout
}

// ============================================================================
// Game State
// ============================================================================

export interface GameState {
  // Meta
  version: string;
  lastSaved: number;
  lastPlayed: number;
  
  // Core Counters
  money: number;
  reputation: number;
  currentDay: number;
  food: number;  // Food resource generated by cafeterias
  
  // Residents
  residents: Resident[];
  graduatedCount: number;
  
  // Grid & Building
  grid: Grid;
  rooms: Room[];
  
  // Fundraisers
  activeFundraisers: Fundraiser[];
  
  // Timers
  nextDonationCheck: number;
  nextMaintenanceCheck: number;
  nextDayNightTransition: number;
  currentPhase: DayPhase;
  nextResidentSpawn: number;
  
  // Settings
  foodPortionSetting: FoodPortionSetting;
}

// ============================================================================
// Profile Specifications
// ============================================================================

export interface ResidentProfileSpec {
  profile: ResidentProfile;
  lifeFillRate: number;
  happinessDecayRate: number;
  fundraiserEfficiency: number;
  graduationBonus: number;
  displayName: string;
  icon: string;
}

// ============================================================================
// Utility Types
// ============================================================================

export interface PlacementResult {
  success: boolean;
  error?: string;
}
