import React, { useState, useEffect } from 'react';
import { GameState } from '../types';
import './HUD.css';

interface HUDProps {
  gameState: GameState;
  onPauseToggle?: () => void;
  isPaused?: boolean;
  onSettingsClick?: () => void;
}

/**
 * HUD component displaying game stats
 */
export const HUD: React.FC<HUDProps> = ({ gameState, onPauseToggle, isPaused = false, onSettingsClick }) => {
  const [timeRemaining, setTimeRemaining] = useState<string>('0:00');
  const [phaseProgress, setPhaseProgress] = useState<number>(0);
  const [donationTimer, setDonationTimer] = useState<string>('0:00');
  const [maintenanceTimer, setMaintenanceTimer] = useState<string>('0:00');
  
  // Update time remaining every second
  useEffect(() => {
    const updateTimer = () => {
      const now = Date.now();
      const remaining = Math.max(0, gameState.nextDayNightTransition - now);
      
      const minutes = Math.floor(remaining / 60000);
      const seconds = Math.floor((remaining % 60000) / 1000);
      setTimeRemaining(`${minutes}:${seconds.toString().padStart(2, '0')}`);
      
      // Calculate progress
      const duration = gameState.currentPhase === 'day' ? 8 * 60 * 1000 : 4 * 60 * 1000;
      const elapsed = duration - remaining;
      const progress = Math.max(0, Math.min(100, (elapsed / duration) * 100));
      setPhaseProgress(progress);
      
      // Donation timer
      const donationRemaining = Math.max(0, gameState.nextDonationCheck - now);
      const donationMin = Math.floor(donationRemaining / 60000);
      const donationSec = Math.floor((donationRemaining % 60000) / 1000);
      setDonationTimer(`${donationMin}:${donationSec.toString().padStart(2, '0')}`);
      
      // Maintenance timer
      const maintenanceRemaining = Math.max(0, gameState.nextMaintenanceCheck - now);
      const maintenanceMin = Math.floor(maintenanceRemaining / 60000);
      const maintenanceSec = Math.floor((maintenanceRemaining % 60000) / 1000);
      setMaintenanceTimer(`${maintenanceMin}:${maintenanceSec.toString().padStart(2, '0')}`);
    };
    
    updateTimer();
    const interval = setInterval(updateTimer, 1000);
    
    return () => clearInterval(interval);
  }, [gameState.nextDayNightTransition, gameState.currentPhase, gameState.nextDonationCheck, gameState.nextMaintenanceCheck]);
  
  // Get reputation color
  const getReputationColor = (rep: number): string => {
    if (rep <= 20) return '#ff0000';
    if (rep <= 40) return '#ff6600';
    if (rep <= 60) return '#ffcc00';
    if (rep <= 80) return '#66cc00';
    return '#00cc00';
  };
  
  // Get food icon
  const getFoodIcon = (setting: string): string => {
    const icons: Record<string, string> = {
      large: '🍽️',
      standard: '🍲',
      small: '🥄',
      none: '❌'
    };
    return icons[setting] || '🍲';
  };
  
  return (
    <div className="hud">
      <div className="hud-section">
        <div className="hud-item" title="Current shelter funds">
          <span className="hud-label">💰 Money:</span>
          <span className="hud-value" style={{ color: gameState.money < 0 ? '#ff4444' : '#ffffff' }}>
            ${gameState.money}
          </span>
        </div>
        <div className="hud-item" title="Community reputation (0-100%)">
          <span className="hud-label">⭐ Reputation:</span>
          <span className="hud-value" style={{ color: getReputationColor(gameState.reputation) }}>
            {gameState.reputation}%
          </span>
        </div>
        <div className="hud-item" title="Food resource generated by cafeterias">
          <span className="hud-label">🍞 Food:</span>
          <span className="hud-value">{gameState.food}</span>
        </div>
      </div>
      
      <div className="hud-section">
        <div className="hud-item">
          <span className="hud-label">👥 Residents:</span>
          <span className="hud-value">{gameState.residents.length}</span>
        </div>
        <div className="hud-item">
          <span className="hud-label">🎓 Graduated:</span>
          <span className="hud-value">{gameState.graduatedCount}</span>
        </div>
        {gameState.activeFundraisers && gameState.activeFundraisers.length > 0 && (
          <div className="hud-item">
            <span className="hud-label">🎪 Fundraisers:</span>
            <span className="hud-value">{gameState.activeFundraisers.length}</span>
          </div>
        )}
      </div>
      
      <div className="hud-section">
        <div className="hud-item">
          <span className="hud-label">📅 Day:</span>
          <span className="hud-value">{gameState.currentDay}</span>
        </div>
        <div className="hud-item">
          <span className="hud-label">🏠 Rooms:</span>
          <span className="hud-value">{gameState.rooms.length}</span>
        </div>
      </div>
      
      <div className="hud-section">
        <div className="hud-item">
          <span className="hud-label">{getFoodIcon(gameState.foodPortionSetting)} Food:</span>
          <span className="hud-value">{gameState.foodPortionSetting}</span>
        </div>
        <div className="hud-item">
          <span className="hud-label">💝 Donation:</span>
          <span className="hud-value">{donationTimer}</span>
        </div>
      </div>
      
      <div className="hud-section">
        <div className="hud-item">
          <span className="hud-label">🔧 Maintenance:</span>
          <span className="hud-value">{maintenanceTimer}</span>
        </div>
      </div>
      
      <div className="hud-section hud-phase-section">
        <div className="hud-phase-info">
          <div className="hud-phase-header">
            <span className="hud-phase-icon">
              {gameState.currentPhase === 'day' ? '☀️' : '🌙'}
            </span>
            <span className="hud-phase-label">
              {gameState.currentPhase === 'day' ? `Day ${gameState.currentDay}` : 'Night'}
            </span>
            <span className="hud-phase-time">{timeRemaining}</span>
          </div>
          <div className="hud-phase-progress">
            <div 
              className={`hud-phase-progress-bar ${gameState.currentPhase}`}
              style={{ width: `${phaseProgress}%` }}
            />
          </div>
        </div>
      </div>
      
      <div className="hud-section hud-controls">
        {onPauseToggle && (
          <button
            className={`hud-button hud-pause-button ${isPaused ? 'paused' : ''}`}
            onClick={onPauseToggle}
            title={isPaused ? 'Resume (Space)' : 'Pause (Space)'}
          >
            {isPaused ? '▶️' : '⏸️'}
          </button>
        )}
        {onSettingsClick && (
          <button
            className="hud-button hud-settings-button"
            onClick={onSettingsClick}
            title="Settings"
          >
            ⚙️
          </button>
        )}
      </div>
    </div>
  );
};
